#include <stdio.h>
#include "VnV.h"

//Autogenerated Registration file for fortran package

INJECTION_REGISTRATION(fortran) {
    printf("HEEEEEEE\n");
}

registrationCallBack vnv_fortran_registration(){
    return VNV_REGISTRATION_CALLBACK_NAME(fortran);
}
