! Autogenerated module for libvnvfortraion package. 

module libvnvfortran
    
    use iso_c_binding
    implicit none
    private
    public :: vnv_fortran_registration

    interface
        
  ! void functions maps to subroutines
    TYPE(C_PTR) function vnv_fortran_registration_c() bind(C, name="vnv_fortran_registration")
        use iso_c_binding
        implicit none
    end function

    end interface

contains ! Implementation of the functions. We just wrap the C function here.
    
    function vnv_fortran_registration() result(ptr)
        TYPE(C_PTR) :: ptr
        ptr = vnv_fortran_registration_c();
    end function
    
end module