before_script:
  - rm -rf install

build_with_adios:
  script:
    - mkdir -p build/with_adios
    - cd build/with_adios
    - cmake ../../
    - make
    - cd test
    - ./test-runner
    - cd ../examples/dummy/executables
    - ./sample.a
    - cd ../c_executables
    - ./csample.a
    
build_without_adios:
  script:
    - mkdir -p build/without_adios
    - cd build/without_adios
    - cmake -DWITH_ADIOS_ENGINE=0 ../../
    - make
    - cd test
    - ./test-runner
    - cd ../examples/dummy/executables
    - ./sample.a
    - cd ../c_executables
    - ./csample.a

test_gen_script:
   script:
   - mkdir -p build/test-gen-script
   - cd test 
   - ./gen.py TestingTheGenerationScript
   - cd ../build/test-gen-script
   - cmake -DWITH_ADIOS_ENGINE=0 ../../
   - make
   - cd test
   - ./test-runner
   - cd ../../../test
   - ./gen.py --r TestingTheGenerationScript
   - cd ../build/test-gen-script
   - make
   - cd test
   - ./test-runner


build_docs:
  script:
    - mkdir -p build/docs/
    - cd build/docs/
    - cmake ../../
    - make docs
    - rm -rf /usr/local/http/vv-neams-1
    - cp -r docs/html /usr/local/http/vv-neams-1 #local-server has a python docs running on 192.168.10.137:5999
    - rm -rf /usr/local/http/vv-neams-doxy 
    - cp -r docs/_build/html /usr/local/http/vv-neams-doxy


