

FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV llvm_version=12
ENV TZ=America/New_York

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install \
    build-essential \
    wget \
    git \
    snap \
    lsb-release \
    software-properties-common \
		zlib1g-dev \
		libssl-dev \
		bzip2 \
    doxygen \
    swig \
    python-dev \
    python3-dev \
    python3-pip \
		libfftw3-dev \
		bear \
		bison \
		flex	\
    gcc\
    g++\
    gfortran\
    libboost-all-dev \
    libblas-dev \
    liblapack-dev \
    gsl-bin \
    libgsl-dev \
    perl \
    libblas64-3

RUN mpicc -show 

RUN pip3 install virtualenv 

#Install cmake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' |  tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN rm /usr/share/keyrings/kitware-archive-keyring.gpg
RUN apt-get install kitware-archive-keyring
RUN apt-get install -y cmake
RUN cmake --version 

#Install llvm
RUN wget https://apt.llvm.org/llvm.sh && chmod u+x ./llvm.sh && ./llvm.sh ${llvm_version} && rm ./llvm.sh && apt-get install -y libclang-12-dev  
ENV LLVM_DIR=/usr/lib/llvm-${llvm_version}

#Install adios
ENV ADIOS_DIR=/root/software/adios
RUN mkdir /root/software && git clone https://github.com/ornladios/ADIOS2.git ADIOS && mkdir adios2-build && cd adios2-build \
  && cmake -DCMAKE_INSTALL_PREFIX=${ADIOS_DIR} ../ADIOS && make -j 16 && make install && cd .. && rm -r adios2-build \
  && rm -r ADIOS 

#Install PAPI (used in the plugins)
RUN git clone https://bitbucket.org/icl/papi.git 
RUN cd papi/src && ./configure && make && make install

