#ifndef VNV_FILES_INTERFACE_H
#define VNV_FILES_INTERFACE_H

#include "common-interfaces/all.h"

VNVEXTERNC void _VnV_registerFile(VnV_Comm comm, const char *packageName,
                                  const char *name, int input,
                                  const char *reader, const char *infilename,
                                  const char *outfilename);

#define ___INJECTION_FILE(PNAME, NAME, COMM, INPUT_BOOL, READER, INFILENAME, OUTFILENAME)  \
  _VnV_registerFile(COMM, VNV_STR(PNAME), #NAME, INPUT_BOOL, READER, INFILENAME, OUTFILENAME);

#define INJECTION_FILE(PNAME, COMM, NAME, INPUT, READER, FILENAME, OUTFILENAME) \
  ___INJECTION_FILE(PNAME,NAME,COMM,INPUT,READER,INFILENAME,OUTFILENAME)

#define INJECTION_INPUT_FILE_(PNAME, NAME, COMM, READER, INFILENAME, OUTFILENAME) \
  ___INJECTION_FILE(PNAME, NAME, COMM, 1, READER, INFILENAME, OUTFILENAME)

#define INJECTION_OUTPUT_FILE_(PNAME, NAME, COMM, READER, INFILENAME, OUTFILENAME) \
  ___INJECTION_FILE(PNAME, NAME, COMM, 0, READER, INFILENAME, OUTFILENAME)

#define INJECTION_INPUT_FILE(PNAME, NAME, COMM, INFILENAME, OUTFILENAME)       \
  INJECTION_INPUT_FILE_(PNAME, NAME, COMM, "auto", INFILENAME, OUTFILENAME)

#define INJECTION_OUTPUT_FILE(PNAME, NAME, COMM, INFILENAME, OUTFILENAME)      \
  INJECTION_OUTPUT_FILE_(PNAME, NAME, COMM, "auto", INFILENAME, OUTFILENAME)



#endif
