#!/bin/env python3

import sys
import os
import json



reg_file_name = os.path.expanduser("~/.vnv")

if os.path.exists(reg_file_name):
    with open(reg_file_name,'r') as f:
        try:
            REGISTRATION = json.load(f)
        except:
            print("Registration file is corrupt")
            exit(1)
else:
    REGISTRATION = { "gui" : {}, "plugin" : {}}


with open(sys.argv[1],'r') as ff:
    a = json.load(ff)
    REGISTRATION["plugin"].update(a.get("plugin",{}))
    REGISTRATION["gui"].update(a.get("gui",{}))
    
with open(reg_file_name, 'w') as f:
    json.dump(REGISTRATION,f, indent=4)
    
    