#!/bin/env python3

import sys
import os
import json


if len(sys.argv) != 4:
    print("Usage Error python app ")
    exit(1)

if sys.argv[1] not in ["gui","plugin"]:
    print("Unknown reg type ", sys.argv[1], " Should be in ", ["gui","plugin"])
    exit(1)
    
if not os.path.exists(sys.argv[3]):
    print("Registration file does not exist")
    exit(1)

try:
    with open(sys.argv[3],'r') as ff:
        json.load(ff)
except Exception as e:
    print(e)
    print("Registration file provided is not valid json")
    exit(1)
    

reg_file_name = os.path.expanduser("~/.vnv")

if os.path.exists(reg_file_name):
    with open(reg_file_name,'r') as f:
        try:
            REGISTRATION = json.load(f)
        except:
            print("Registration file is corrupt")
            exit(1)
else:
    REGISTRATION = { "gui" : {}, "plugin" : {}}


REGISTRATION[sys.argv[1]][sys.argv[2]] = sys.argv[3]
    
with open(reg_file_name, 'w') as f:
    json.dump(REGISTRATION,f, indent=4)
    
    