#!/bin/env python3

import sys
import os
import json


reg_file_name = os.path.expanduser("~/.vnv")
conf = {}
try:
    with open(reg_file_name, 'r') as ff:
        conf = json.load(ff)
except:
    conf = {}

if sys.argv[1] == "executable":

    if len(sys.argv) < 4:
        print("Usage Error python app ")
        exit(1)

    if "executables" not in conf:
        conf["executables"] = {}
        
    conf["executables"][sys.argv[2]] = {
        "filename": sys.argv[3],
        "description": " ".join(sys.argv[4:])
    }


elif sys.argv[1] == "executablep":

    if len(sys.argv) < 5:
        print("Usage Error python app ")
        exit(1)

    if "executables" not in conf:
        conf["executables"] = {}
        
    conf["executables"][sys.argv[2]] = {
        "filename": sys.argv[3],
        "defs" : {
            "args" : sys.argv[4]
        },
        "description": " ".join(sys.argv[5:])
    }
        
    
elif sys.argv[1] == "plugin":

    if len(sys.argv) != 4:
        print("Usage Error python app ")
        exit(1)

    if "plugins" not in conf:
        conf["plugins"] = {}
    conf["plugins"][sys.argv[2]] = sys.argv[3]

elif sys.argv[1] == "report":

    if len(sys.argv) != 4:
        print("Usage Error python app ")
        exit(1)

    if "reports" not in conf:
        conf["reports"] = {}
    conf["reports"][sys.argv[2]] = sys.argv[3]

else:
    print("Unknown reg type ", sys.argv[1], " Should be in ", [
          "executable", "plugin", "report"])
    exit(1)

with open(reg_file_name, 'w') as f:
        json.dump(conf, f, indent=4)
